### PR TITLE
Set Python home on linux

### PR DESCRIPTION
**Pull request by est77**

### CODE REVIEW

**Comment by est77** [comment]
I need this for my build. Otherwise, I have in studio the "ImportError: No module named site" error.
Calling Py_SetPythonHome() fixes the new build and it does not seem to affect the previous build.

**Comment by dictoon** [comment]
Is this fix included in the Linux 1.9.0 build that you made and uploaded yesterday?

**Comment by est77** [comment]
Yes. I included it after testing it in my computers.

**Comment by dictoon** [comment]
Ok, cool. Merging!

**Pull request merged**
