### PR TITLE
Travis containers update

### PR DESCRIPTION
**Pull request by est77**
Issue #788.

Switch to container based builds. This cuts building time by more than 50%,
from 24 mins to 10 mins approx.

The good points:

- Builds start much faster now.
- We can use 2 cores for building.

The bad points:

- It seems it's not possible to update gcc to 4.8 like we did before. Since our deps are build with gcc 4.8, this could be a problem at some point. So far it seems to work.

Also, removed an unused clang format file.

### CODE REVIEW

**Comment by dictoon** [comment]
Cool!

Maybe squash the last three commits into a single one before merging?

**Comment by est77** [comment]
Yes. It's still work in progress, not ready to be merged yet. 
I'm not being able to install gcc 4.8 at the moment.

**Comment by est77** [comment]
Merged, with the idea of rolling back if we have problems and don't find a way to install gcc 4.8.

**Comment by dictoon** [comment]
As far as I can tell, you have closed the PR, not merged it.

**Pull request merged**
