### PR TITLE
Fix camera movement bug 

### PR DESCRIPTION
**Pull request by aytekaman**
First version of the fix for #1451.

### CODE REVIEW

**Comment by aytekaman** [comment]
There is a problem with the file format i think. I will fix that.

**Comment by dictoon** [comment]
Thanks!

Looks like line endings have changed, yes.

**Comment by dictoon** [comment]
Woops, my review comments are shown as outdated (because you pushed your line endings fix just before my review).

**Comment by dictoon** [comment]
Thanks a lot!

**Comment by aytekaman** [comment]
You are welcome!

**Pull request merged**
