### PR TITLE
OSL BSSRDF fixes & test suite update

### PR DESCRIPTION
**Pull request by est77**

### CODE REVIEW

**Comment by Narann** [comment]
Looking at the images, some new results look weird on the contact plane.

**Comment by dictoon** [comment]
I kind of agree, actually. Esteban, can you remind me again why you modified the non-OSL test scenes?

**Comment by est77** [comment]
I added UV coordinates to the box and the sphere, for the bump tests.

**Comment by dictoon** [comment]
Ah, right. For some reason it seems to lead to noticeably more noise on the floor planes...

**Pull request merged**
