### PR TITLE
Update attribute editor when clearing crop window #1258

### PR DESCRIPTION
**Pull request by aiivashchenko**

### CODE REVIEW

**Comment by dictoon** [comment]
Pretty much perfect, thanks!

I only have two minor suggestions regarding naming:

- I would suggest `signal_crop_window_cleared` for the signal emitted by `MainWindow` because, as far as `MainWindow` is concerned, all it knows is that the crop window was cleared; it doesn't necessarily know that in consequence to that signal, a widget will be cleared...

- I would suggest `slot_clear_crop_window_widget` for the slot, because that's the terminology we used: the user interface is made of widgets...

These are really details. The code is simple, clear and expressive. Excellent work!

**Comment by dictoon** [comment]
Note that you can simply push a new commit, it will automatically get added to this PR.

**Comment by aiivashchenko** [comment]
@dictoon, thank you for the review, 
Signal and slot are named now as requested.

**Comment by dictoon** [comment]
Perfect, merging! Thank you

**Pull request merged**
