### PR TITLE
Moving Frame::write() and Frame::archive()

### PR DESCRIPTION
**Pull request by jsxs0**
Just the framework to move files. Actual code would be in CMakeLists.txt
This is a fix to the issue appleseedhq#42 (appleseedhq#42). So basically, this is just to move to the frame::write().
For the function calls to be implemented (in a separate file), I'd recommend the following, if they work:
```
bool FrameArchiver::archive(
const char* directory,
char** output_path)
std::string fileName = name;
fileName += "/.";
std::string namestring = BASE_PATH;
namestring+= name;
if (output_path)
*output_path = duplicate_string(file_path.c_str());


````
If this can work.

### CODE REVIEW

**Comment by dictoon** [comment]
I'm sorry, I don't follow. Why are you commiting a text file with the content of our CMakeLists.txt file?

**Comment by jsxs0** [comment]
> I'm sorry, I don't follow. Why are you commiting a text file with the content of our CMakeLists.txt file?

Why did I commit a text file with the content of **your** CMakeLists.txt file? Well, because I needed to create two new pairs of files (framewriter.{h,cpp} and framearchiver.{h,cpp}), and, then, add them to the CMakeLists.txt file, and move the code over to these new files.
Now, to make all this of this happen, I committed the file (Maybe for future references), and I'll writing out the code for both the files, and then can move them!
Hope this helps!

**Comment by dictoon** [comment]
You can just commit your changes and GitHub will show the difference between the branch you're intending to merge the PR into (master) and your changes.

**Comment by jsxs0** [comment]
Now, as far as the code for ` Frame::archive()` is concerned, I had couple of approaches to go with, which ones should I go with?
With this algorithmic approach:
```
bool Frame::archive(
    const char*         directory,
    char**              output_path) const
{
    assert(directory);
    const string filename =
        "autosave." + get_time_stamp_string() + ".exr";
    const string file_path = (filesystem::path(directory) / filename).string();
    if (output_path)
        *output_path = duplicate_string(file_path.c_str());
    Image transformed_image(*impl->m_image);
    transform_to_output_color_space(transformed_image);

    return
        write_image(
            file_path.c_str(),
            transformed_image,
            ImageAttributes::create_default_attributes());
}

```
**OR**
```
image::object archive_frame(const Frame* frame, const char* directory)
    {
        char* output = 0;
        if (frame->archive(directory, &output))
        {
            const image::str path(output);
            foundation::free_string(output);
            return path;
        }
        return bpy::object();
    }
```
**OR**
```
int addDir(const char* name) {
    std::string fileName = name;
    fileName += "/.";

    if (g_debugLevel > 0) {
      std::cout << "Creating dir: " << fileName << std::endl;
    }

    std::string nametemp= BASE_PATH;
    nametemp += name;
    int res = emulate_vfs_mkdir(nametemp.c_str(), O_CREAT);
    if (res < 0) {
      std::cerr << "Cannot create dir" << std::endl;
    }
    return 0;
}
int addFile(char* name, const char* path) {
    //spiffs_metadata_t meta;

    FILE* src = fopen(path, "rb");
    if (!src) {
        std::cerr << "error: failed to open " << path << " for reading" << std::endl;
        return 1;
    }


    std::string nametemp = BASE_PATH;
    nametemp += name;

    const int flags = O_CREAT | O_TRUNC | O_RDWR;
    int fd = emulate_esp_vfs_open(nametempc_str(), flags, 0);
    if (fd < 0) {
        std::cerr << "error: failed to open \"" << nametemp << "\" for writing" << std::endl;
        return 0;
    }

    fseek(src, 0, SEEK_END);
    size_t size = ftell(src);
    fseek(src, 0, SEEK_SET);

    if (g_debugLevel > 0) {
        std::cout << "file size: " << size << std::endl;
    }

    size_t left = size;
    uint8_t data_byte;
    while (left > 0){
        if (1 != fread(&data_byte, 1, 1, src)) {
            std::cerr << "fread error!" << std::endl;
            fclose(src);
            emulate_esp_vfs_close(fd);
            return 1;
        }
        ssize_t res = emulate_esp_vfs_write(fd, &data_byte, 1);
        if (res < 0) {
            std::cerr << "esp_vfs_write() error" << std::endl;
            if (g_debugLevel > 0) {
                std::cout << "data left: " << left << std::endl;
            }
            fclose(src);
            emulate_esp_vfs_close(fd);
            return 1;
        }
        left -= 1;
    }

    emulate_esp_vfs_close(fd);
    // Get the system time to file timestamps
//    meta.atime = time(NULL);
//    meta.ctime = meta.atime;
//    meta.mtime = meta.atime;
//    SPIFFS_update_meta(&s_fs, name, &meta);

    fclose(src);

    return 0;
}

```
**OR**
```
static std::istream &openIn(const char *fileName, std::ifstream &ifs) {
  if (isChar(fileName, '-')) return std::cin;
  ifs.open(fileName);
  if (!ifs) err("can't open file: " + std::string(fileName));
  return ifs;

```
**OR**
```
bpy::object archive_frame(const FrameArchiver* frameArchiver, const char* directory)
    {
        char* output = 0;

        if (frameArchiver->archive(directory, &output))
        {
            const bpy::str path(output);
            foundation::free_string(output);
            return path;
        }

        // Return None.
        return bpy::object();
    }

```
Now, with these many approaches for `Frame::archive()`, with which of the following approach should I move ahead?
Kindly suggest me the best ones to of the plausible ones given above.
Thanks!

**Comment by jsxs0** [comment]
> You can just commit your changes and GitHub will show the difference between the branch you're intending to merge the PR into (master) and your changes.

Okay, so shall I delete the CMakeLists.txt file from the commits tab even though I've made some changes to it?

**Comment by dictoon** [comment]
Are you randomly copy/pasting code from the web? Please, choose the approach that suits you best, implement it, test it and push your code here so that we can discuss your choices.

**Comment by jsxs0** [comment]
> Are you randomly copy/pasting code from the web? Please, choose the approach that suits you best, implement it, test it and push your code here so that we can discuss your choices.

No, obviously not. Why'd I just _randomly copy/past code_ from anywhere? GSoC has it's own prestige, and appleseed is one of the best rendering engine designed for animation and visual effects, keeping these things in mind, why'd I just do that?
And to be precise, 2 approaches suit me. I was just a bit confused, and ended up sticking the wrong code at the wrong place. Sure, I'll try out both of them, and implement them, test them, and then push them here in the draft PR, and then we discuss.
Sure, thanks!

**Comment by dictoon** [comment]
Please see https://github.com/appleseedhq/appleseed/pull/2494#issuecomment-476511006.

**Pull request closed without merging**
