### PR TITLE
Change OSL to Version 1.11.9 and LLVM to Version 9

### PR DESCRIPTION
**Pull request by LZaw**
Before merging, I still have to update OSL in the Linux and Windows dependency package, to have every OS work on the same (major) version.

### CODE REVIEW

**Review by oktomus — APPROVED** [review]
Thank you ! Can't wait to see that "build fail" on each PR disappear 🤣

**Comment by theartful** [comment]
I think the change in #2900 (in the cmake file) should fix the `function was not declared` errors in osl.

**Review by Mango-3 — COMMENTED** [review]
line 168    `-DWITH_DISNEY_MATERIAL=ON \` should be removed. We don't use the Disney material anymore. It has been removed from the sources with commit 1e8e30c72d782b478467a1ec5cf9e13d710c49ac

**Comment by LZaw** [comment]
Thank you for the hint.
I removed it, as well as the SeExpr.

**Pull request closed without merging**
