### PR TITLE
Improve entity editor in .studio, add alternative volume parameterization to glass BSDF

### PR DESCRIPTION
**Pull request by dictoon**

### CODE REVIEW

**Comment by est77** [comment]
Do we need to set the parameterization here: https://github.com/appleseedhq/appleseed/blob/master/src/appleseed/renderer/modeling/bsdf/oslbsdf.cpp#L365

or it will pick the default?

**Comment by est77** [comment]
I think that closure parameters can be renamed as long as they are not keyword parameters.
They are matched by position and not by name.

**Comment by dictoon** [comment]
> Do we need to set the parameterization here

Good point, yes we need to. I'll add it.

**Comment by dictoon** [comment]
> I think that closure parameters can be renamed as long as they are not keyword parameters.

Ah, right, good point. I will rename them then, and test that everything still works.

**Pull request merged**
