### PR TITLE
Add metal and plastic osl materials for 3ds max

### PR DESCRIPTION
**Pull request by usakhelo**
Hi,
This PR adds plastic and metal osl shaders for 3ds max. I just copied them from gaffer/surface folder and renamed output closure.

### CODE REVIEW

**Comment by dictoon** [comment]
Looks good to me! Are these straight copies of existing shaders?

In any case I'd appreciate a review by @luisbarrancos.

**Comment by luisbarrancos** [comment]
LGTM as well. It's consistent with the shader library and remaining DCC plugins.

**Comment by dictoon** [comment]
Thanks Luis!

**Comment by usakhelo** [comment]
Sorry for late reply - yes it's straight copy. Only output variable name is different.
Thanks for review.

**Pull request merged**
