### PR TITLE
SSS work

### PR DESCRIPTION
**Pull request by est77**
- Refactored exponential distribution sampling functions.
- Cleanup SSS tests.
- Ignore CMake 3.0 warnings.

### CODE REVIEW

**Comment by est77** [comment]
> In fact, I think mappings.h and sampling.h should be merged into one. They have the same purpose: mapping uniform random numbers in [0,1)^N to various domains.

Ok. Maybe renaming mappings to sampling.h and moving the exponential sampling there?

**Comment by est77** [comment]
> I liked these plots... Why did you remove them?

I'm planning to rewrite the Dirpole tests and plots.

**Comment by dictoon** [comment]
> Ok. Maybe renaming mappings to sampling.h and moving the exponential sampling there?

I would advise to keep `mappings.h` for the simple reason that header files with the same name as a module (`sampling` here) are already used to include all files of the module.

For instance, `foundation/math/knn.h` is a "shortcut file" to include all files under `foundation/math/knn/`. We have these "shortcut files" for modules where it makes no sense to include only some of the files. Examples of such modules are `knn`, `bsp`, `bvh`, etc.

**Comment by dictoon** [comment]
> I'm planning to rewrite the Dirpole tests and plots.

Ok.

**Comment by est77** [comment]
Fixed & rebased.

**Comment by dictoon** [comment]
Thanks!

**Pull request merged**
